# Generated by Django 5.1.2 on 2025-03-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Progress Bars',
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_no', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('account_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('product_family', models.CharField(blank=True, max_length=255, null=True)),
                ('protein_family', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(max_length=10)),
                ('fiscal_quarter', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_month', models.CharField(blank=True, max_length=255, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(max_length=255)),
                ('quantity_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('freight_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('freight_price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_charge_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=2)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_forecast', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Revenue Analytics',
                'verbose_name_plural': 'Revenue Analytics',
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='VolumeForecasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quarter', models.CharField(max_length=20)),
                ('historical_quantity', models.FloatField()),
                ('forecast_quantity', models.FloatField()),
                ('is_forecast', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('account_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('product_family', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('product_name', 'quarter', 'region', 'account_owner', 'product_family')},
            },
        ),
    ]
